### ISSUE TITLE
Plugin failure: tldraw TypeError: Cannot define property Symbol(Symbol.metadata), object is not extensible

### ISSUE THREAD

**Issue by ksdavidc** [holxsam/tldraw-in-obsidian#50]
I can't install (from obsidian, not BRAT). I get an error like this:

```
Plugin failure: tldraw TypeError: Cannot define property Symbol(Symbol.metadata), object is not extensible
    at defineProperty (<anonymous>)
    at __defNormalProp (VM2789 plugin:tldraw:16:57)
    at __decoratorMetadata (VM2789 plugin:tldraw:49:47)
    at __decorateElement (VM2789 plugin:tldraw:76:15)
    at pluginBuild (VM2789 plugin:tldraw:93864:30)
    at __decorateElement (VM2789 plugin:tldraw:71:28)
    at anonymous (VM2789 plugin:tldraw:94806:16)
    at e.<anonymous> (app.js:1:2292629)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)

```
[tldraw.log](https://github.com/user-attachments/files/17016854/tldraw.log)

Looks like a conflict with a plugin...but i have too many to look at. Any clues I could use to narrow it down?

**Comment by jon-dez** [comment]
Hmm, that's weird. Can you try creating a new temporary vault with only this plugin installed? If the issue still persists could you provide more information, e.g. plugin version, Obsidian version, and perhaps a list of plugins that you have installed?

**Comment by jon-dez** [comment]
@ksdavidc any update?

**Comment by jon-dez** [comment]
Fixed in the latest release!
